# Generated by Django 5.0.7 on 2024-12-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_addcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddCourse',
        ),
    ]
